Added NFT marketplace
gear-tech/apps pull request #32
Opened 2022-03-08 16:35 UTC by LouiseMedova

2022-03-10 10:41 UTC, grishasobol requested changes
Wow, I'm impressed, great work

2022-03-10 10:41 UTC, grishasobol commented on nft-marketplace/marketplace/Cargo.toml
> +[workspace]
end of line in the end of file

2022-03-10 10:41 UTC, grishasobol commented on nft-marketplace/nft/src/lib.rs
> +// #[no_mangle]
What is it?

2022-03-10 10:41 UTC, grishasobol commented on nft-marketplace/nft/Cargo.toml
> +[workspace]
EOL in the EOF

2022-03-10 10:41 UTC, grishasobol commented on nft-marketplace/marketplace/src/lib.rs
> +// #[no_mangle]
what is it?

2022-03-10 10:41 UTC, grishasobol commented on nft-marketplace/nft/royalties/Cargo.toml
> +primitive-types = { version = "0.10.1", default-features = false, features = ["scale-info"]}
eol in the eof

2022-03-11 10:00 UTC, gshep commented on nft-marketplace/marketplace/io/src/lib.rs
> +    pub bids: Option<Vec<Bid>>,
Does this really need to be Option? Empty vectory doesn't mean the same as `Option::None` in this case?

2022-03-11 10:19 UTC, gshep commented on nft-marketplace/marketplace/src/auction.rs
> +        item.auction = None;
If I'm not mistaken this variable is not used in either if-else blocks so could be made right after clone:
```rust
        let auction = item.auction.clone().expect("Auction doesn not exist");
        if auction.ended_at > exec::block_timestamp() {
            panic!("Auction is not over");
        }
        
        item.auction = None;
```

2022-03-11 10:20 UTC, gshep commented on nft-marketplace/marketplace/src/auction.rs
> +            let highest_bid = &bids[bids.len() - 1].clone();
It would be nice if you could make guarantee that the vector is sorted on the type level.

2022-03-11 10:30 UTC, gshep commented on nft-marketplace/marketplace/src/auction.rs
> +        if !bids.is_empty() {
This if also could be rewritten to deacrease nesting and make the code more consequent. I'm not insisting though =)
```suggestion
        let mut bids = auction.bids.unwrap_or_default();
        if bids.is_empty() {
             msg::reply(
                MarketEvent::AuctionCancelled {
                    nft_contract_id: *nft_contract_id,
                    token_id,
                },
                0,
            );
            
            return;
        }
        
        let highest_bid = &bids[bids.len() - 1].clone();
        bids.pop();
        for bid in bids {
            transfer_payment(&exec::program_id(), &bid.id, item.ft_contract_id, bid.price)
                .await;
        }
        // fee for treasury
        // ...
```

2022-03-18 17:19 UTC, gshep approved these changes

2022-04-05 11:35 UTC, grishasobol approved these changes

2022-04-06 11:23 UTC, shamilsan approved these changes

2022-04-07 20:08 UTC, merged