Concert contract
gear-tech/apps pull request #44
Opened 2022-04-24 08:08 UTC by Akado2009

Resolves # .

- Implements a concert contract on top of ERC1155 multi-token.
- 
@reviewer-or-team

2022-05-11 07:15 UTC, shamilsan commented on concert/src/lib.rs
> +        ..Concert::default()
`Default::default()` is more canonic.
```suggestion
        ..Default::default()
```

2022-05-11 07:15 UTC, shamilsan commented on concert/src/lib.rs
> +        mtd.into_iter().enumerate().for_each(|(_i, meta)| {
Why enumerate if you don't use `i`? Also, it is more readable to use `for` loop here instead of `for_each`.

2022-05-11 07:15 UTC, shamilsan commented on concert/src/lib.rs
> +            let _actor_md = self.metadata.get(actor);
Don't use an underscore at the beginning if you use the variable.
```suggestion
            let actor_md = self.metadata.get(actor);
```

2022-05-11 07:15 UTC, shamilsan commented on concert/src/lib.rs
> +            let mut meta: Vec<Option<TokenMetadata>> = vec![];
No need to declare the type.
```suggestion
            let mut ids = vec![];
            let mut amounts = vec![];
            let mut meta = vec![];
```

2022-05-11 07:15 UTC, shamilsan commented on concert/src/lib.rs
> +                date: date,
```suggestion
                date,
```

2022-05-11 07:15 UTC, shamilsan commented on concert/src/lib.rs
> +    pub name: u128,
Maybe `TokenId`?
```suggestion
    pub name: TokenId,
```

2022-05-11 08:09 UTC, shamilsan commented on concert/src/lib.rs
> +        for meta in mtd.iter() {
```suggestion
        for meta in mtd {
```

2022-05-11 08:10 UTC, shamilsan commented on concert/src/lib.rs
> +                .insert(self.id_counter + 1, (*meta).clone());
No need to clone if we consume `mtd`.
```suggestion
                .insert(self.id_counter + 1, meta);
```

2022-05-11 10:17 UTC, shamilsan approved these changes

2022-05-21 17:44 UTC, LouiseMedova commented on concert/io/src/lib.rs
> +pub struct TokenMetadata {
There is no need to define the structs that relate to another contract.

2022-05-21 22:14 UTC, fluiderson requested changes

2022-05-21 22:14 UTC, fluiderson commented on concert/tests/utils.rs
> +    // let ft = Program::mock(&sys, FungibleToken);
Dead code?

2022-05-23 14:34 UTC, fluiderson reviewed
The failure in CI was fixed in #53, so merge `master` into this branch and fix all clippy warnings.

2022-05-23 15:48 UTC, fluiderson approved these changes

2022-05-23 21:58 UTC, merged