WIP: multisig wallet
gear-tech/apps pull request #48
Opened 2022-05-04 06:37 UTC by puzzle-rusher

2022-05-19 09:27 UTC, shamilsan reviewed
Generally, I'd consider using `BTreeSet<T>` instead of `BTreeMap<T, bool>` where it is possible.

2022-05-19 09:27 UTC, shamilsan commented on multisig-wallet/src/lib.rs
> +        self.execute_transaction(transaction_id, None::<fn()>);
Why not just `None`?
```suggestion
        self.execute_transaction(transaction_id, None);
```

2022-05-19 09:27 UTC, shamilsan commented on multisig-wallet/src/lib.rs
> +    pub is_owner: BTreeMap<ActorId, bool>,
Isn't better to use `BTreeSet` here?

2022-05-19 09:27 UTC, shamilsan commented on multisig-wallet/src/lib.rs
> +    pub owners: Vec<ActorId>,
May we combine `owners` and `is_owner` into one collection?

2022-05-19 09:27 UTC, shamilsan commented on multisig-wallet/src/lib.rs
> +            .or_insert(BTreeMap::new())
A little bit shorter:
```suggestion
            .or_default()
```

2022-05-19 09:27 UTC, shamilsan commented on multisig-wallet/src/lib.rs
> +    pub transactions: BTreeMap<U256, Transaction>,
I'd add a type alias for transaction id for readability.
```rust
type TransactionId = U256;
```

2022-05-19 09:27 UTC, shamilsan commented on multisig-wallet/src/lib.rs
> +            .unwrap()
Also, you can use `as` here.

2022-05-19 09:27 UTC, shamilsan commented on multisig-wallet/src/lib.rs
> +    /// executed Include executed transactions.
```suggestion
    /// * `pending` Include pending transactions.
    /// * `executed` Include executed transactions.
```

2022-05-19 09:27 UTC, shamilsan commented on multisig-wallet/src/lib.rs
> +    let config: MWInitConfig = msg::load().expect("Unable to decode InitDao");
Dao?

2022-05-19 09:27 UTC, shamilsan commented on multisig-wallet/src/lib.rs
> +        output : MWEvent,
Spaces.
```suggestion
        input: MWInitConfig,
    handle:
        input: MWAction,
        output: MWEvent,
```

2022-05-19 09:27 UTC, shamilsan commented on multisig-wallet/src/lib.rs
> +            MWAction::decode(&mut bytes.as_slice()).expect("Could not load Action")
Isn't it the same as `msg::load::<MWAction>()`?

2022-05-23 16:09 UTC, shamilsan reviewed
Need to resolve fixed conversations and to comment that are not fixed.

2022-05-23 16:09 UTC, shamilsan commented on multisig-wallet/src/lib.rs
> +            self.change_requirement(self.owners.len().try_into().unwrap());
```suggestion
            self.change_requirement(self.owners.len() as u64);
```

2022-05-24 11:08 UTC, LouiseMedova requested changes
Looks good but tests can be written mush shorter

2022-05-24 12:04 UTC, puzzle-rusher commented on multisig-wallet/src/lib.rs
> +    fn has_owner(&self, owner: &ActorId) -> bool {
I use it like this `self.has_owner(owner)` where self is wallet in this context, so I thought it was more expressive.

2022-05-24 15:05 UTC, LouiseMedova commented on multisig-wallet/src/lib.rs
> +    fn add_transaction(
Need to checks that transaction value is equal to attached value

2022-06-03 15:49 UTC, shamilsan approved these changes
You'll have clippy warnings after merging master, please fix them.

2022-06-12 18:11 UTC, shamilsan commented
Closing in favor https://github.com/gear-dapps/multisig-wallet/pull/1

2022-06-12 18:11 UTC, closed without merging